### ISSUE TITLE
Dataloader returns 0 volumns. No *.nii.gz, *.vti or *.nii inside examples/ct_test directory  

### ISSUE THREAD

**Issue by kitbransby** [fkong7/HeartFFDNet#2]
Hi, when i'm running your `predict.py` out the box, i have an error where the dataloader returns 0 testing volumes and
0 mask volumes. When I dug a little deeper I found that the dataloader was trying to retrieve *.nii.gz, *.vti or *.nii files from inside `examples/ct_test` directory. However, in the google drive link you provided there are not any of those files types in the ct_test directory. 

Is the program supposed to look for files in this directory? Perhaps you can tell me what you think is going wrong

P.s great work on the paper!

**Comment by fkong7** [comment]
Hi, we do not provide image data since they are from public challenges. Please obtain the images from the challenge organizers and put them in the corresponding directory.
