### ISSUE TITLE
Creating dat_of_template_with_no_veins.dat

### ISSUE THREAD

**Issue by kitbransby** [fkong7/HeartFFDNet#3]
When creating a prediction using the MMWHS dataset, can you tell me where the `dat_of_template_with_no_veins.dat` file comes from? Assume it would be created from `template_no_views_normalized.vtp` using `make_control_grid.py`, however i'm getting vtkXMLPolyDataReader errors when executing the following command: 

`python template/make_control_grid.py   --template examples/mmwhs_test/template_with_no_veins_normalized.vtp   --template_im examples/place_holder_image.nii.gz   --num_pts 6`

Any ideas where I'm going wrong? 

P.s the weblink to the MMWHS does not work. I think this is the updated one: https://zmiclab.github.io/zxh/0/mmwhs/ 

full error:
` ERROR: In ../Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x555a68df0770): Algorithm vtkXMLPolyDataReader(0x555a68ef3250) returned failure for request: vtkInformation (0x555a68f86840)
  Debug: Off
  Modified Time: 131
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1

Traceback (most recent call last):
  File "template/make_control_grid.py", line 853, in <module>
    template = process_template(args.template, args.target_node_num, template_im_fn=args.template_im, ref_template_fn=args.ref_template)
  File "template/make_control_grid.py", line 251, in process_template
    template  = transform_polydata(template, img_center2-img_center, transform, SIZE)
  File "template/make_control_grid.py", line 47, in transform_polydata
    coords = map_polydata_coords(poly, displacement, transform, size)
  File "template/make_control_grid.py", line 39, in map_polydata_coords
    coords = vtk_to_numpy(poly.GetPoints().GetData())
AttributeError: 'NoneType' object has no attribute 'GetData' `

**Comment by fkong7** [comment]
Sorry I forgot to put those files in the ``examples`` folder. Both the .dat and the trained weights are now in ``examples/mmwhs``. And yes, that dat file would be created from ``template_no_views_normalized.vtp`` using ``make_control_grid.py``. For your error messages, ``poly.GetPoints()`` returned None. Perhaps it could be an incorrect path to the ``template_no_views_normalized.vtp`` so that the mesh wasn't loaded in?

**Comment by kitbransby** [comment]
Thanks for the upload, I'll mark this as resolved
